# src/translator.py
# All labels hardcoded with Roman Urdu and Urdu script — no internet needed

WORD_LABELS = {
    "10":            ("das",         "دس"),
    "100":           ("sau",         "سو"),
    "2-Hay":         ("do hay",      "دو ہے"),
    "50":            ("pachaas",     "پچاس"),
    "Alifmad":       ("alif madd",   "الف مد"),
    "Aray":          ("aray",        "ارے"),
    "Jeem":          ("jeem",        "جیم"),
    "able":          ("qaabil",      "قابل"),
    "absolutely":    ("bilkul",      "بالکل"),
    "according":     ("ke mutabiq",  "کے مطابق"),
    "all":           ("sab",         "سب"),
    "almost":        ("taqreeban",   "تقریباً"),
    "ancient":       ("qadeem",      "قدیم"),
    "annual":        ("saalana",     "سالانہ"),
    "another":       ("doosra",      "دوسرا"),
    "any":           ("koi bhi",     "کوئی بھی"),
    "baby":          ("bachcha",     "بچہ"),
    "because":       ("kyunke",      "کیونکہ"),
    "both":          ("dono",        "دونوں"),
    "brain":         ("dimagh",      "دماغ"),
    "bus":           ("bas",         "بس"),
    "car":           ("gaari",       "گاڑی"),
    "come":          ("aao",         "آؤ"),
    "continuously":  ("lagaataar",   "لگاتار"),
    "cycle":         ("cycle",       "سائیکل"),
    "do":            ("karo",        "کرو"),
    "dry":           ("khushk",      "خشک"),
    "empty":         ("khaali",      "خالی"),
    "eye":           ("aankh",       "آنکھ"),
    "father":        ("abbu",        "ابو"),
    "few":           ("thore",       "تھوڑے"),
    "from":          ("se",          "سے"),
    "go":            ("jao",         "جاؤ"),
    "he":            ("woh",         "وہ"),
    "heart":         ("dil",         "دل"),
    "help":          ("madad",       "مدد"),
    "however":       ("phir bhi",    "پھر بھی"),
    "i":             ("mein",        "میں"),
    "keep":          ("rakho",       "رکھو"),
    "lakh":          ("laakh",       "لاکھ"),
    "literally":     ("literally",   "لفظی طور پر"),
    "make":          ("banao",       "بناؤ"),
    "many":          ("bohat",       "بہت"),
    "marriage":      ("shaadi",      "شادی"),
    "mother":        ("ammi",        "امی"),
    "mouth":         ("munh",        "منہ"),
    "near":          ("qareeb",      "قریب"),
    "off":           ("band",        "بند"),
    "often":         ("aksar",       "اکثر"),
    "one":           ("aik",         "ایک"),
    "outdoors":      ("bahar",       "باہر"),
    "outside":       ("bahar",       "باہر"),
    "parents":       ("waldain",     "والدین"),
    "request":       ("guzarish",    "گزارش"),
    "say":           ("kaho",        "کہو"),
    "she":           ("woh",         "وہ"),
    "sister":        ("behan",       "بہن"),
    "so-accentuator":("toh",         "تو"),
    "so-in-order-to":("taake",       "تاکہ"),
    "some":          ("kuch",        "کچھ"),
    "soon":          ("jald",        "جلد"),
    "street":        ("gali",        "گلی"),
    "sudden":        ("achanak",     "اچانک"),
    "sufficient":    ("kaafi",       "کافی"),
    "there":         ("wahan",       "وہاں"),
    "this":          ("yeh",         "یہ"),
    "thorough":      ("mukammal",    "مکمل"),
    "tongue":        ("zubaan",      "زبان"),
    "travel":        ("safar",       "سفر"),
    "truck":         ("truck",       "ٹرک"),
    "true":          ("sach",        "سچ"),
    "universal":     ("universal",   "عالمگیر"),
    "up":            ("upar",        "اوپر"),
    "urgent":        ("zaroori",     "ضروری"),
    "very":          ("bohat zyada", "بہت زیادہ"),
    "walk":          ("chalo",       "چلو"),
    "warm":          ("garam",       "گرم"),
    "we":            ("hum",         "ہم"),
    "weak":          ("kamzor",      "کمزور"),
    "whole":         ("poora",       "پورا"),
    "without":       ("baghair",     "بغیر"),
    "woman":         ("aurat",       "عورت"),
    "write":         ("likho",       "لکھو"),
    "you":           ("aap",         "آپ"),
}

ALPHA_LABELS = {
    "A": ("alif",   "اے"),   "B": ("bay",    "بی"),
    "C": ("say",    "سی"),   "D": ("daal",   "ڈی"),
    "E": ("ee",     "ای"),   "F": ("fay",    "ایف"),
    "G": ("gay",    "جی"),   "H": ("hay",    "ایچ"),
    "I": ("ain",    "آئی"),  "J": ("jeem",   "جے"),
    "K": ("kaaf",   "کے"),   "L": ("laam",   "ایل"),
    "M": ("meem",   "ایم"),  "N": ("noon",   "این"),
    "O": ("wao",    "او"),   "P": ("pay",    "پی"),
    "Q": ("qaaf",   "کیو"),  "R": ("ray",    "آر"),
    "S": ("seen",   "ایس"),  "T": ("tay",    "ٹی"),
    "U": ("uu",     "یو"),   "V": ("vay",    "وی"),
    "W": ("wao",    "ڈبلیو"),"X": ("ex",     "ایکس"),
    "Y": ("yay",    "وائی"), "Z": ("zay",    "زی"),
    "0": ("sifar",  "صفر"),  "1": ("aik",    "ایک"),
    "2": ("do",     "دو"),   "3": ("teen",   "تین"),
    "4": ("chaar",  "چار"),  "5": ("paanch", "پانچ"),
    "6": ("chay",   "چھ"),   "7": ("saat",   "سات"),
    "8": ("aath",   "آٹھ"),  "9": ("nau",    "نو"),
}

URDU_ALPHA_LABELS = {
    "1-Hay":    ("1-hay",   "ہ"),
    "Ain":      ("ain",     "ع"),
    "Alif":     ("alif",    "ا"),
    "Bay":      ("bay",     "ب"),
    "Byeh":     ("byeh",    "بے"),
    "Chay":     ("chay",    "چ"),
    "Cyeh":     ("cyeh",    "سے"),
    "Daal":     ("daal",    "ڈ"),
    "Dal":      ("dal",     "د"),
    "Dochahay": ("do chay", "دو چے"),
    "Fay":      ("fay",     "ف"),
    "Gaaf":     ("gaaf",    "گ"),
    "Ghain":    ("ghain",   "غ"),
    "Hamza":    ("hamza",   "ء"),
    "Kaf":      ("kaf",     "ک"),
    "Khay":     ("khay",    "خ"),
    "Kiaf":     ("kiaf",    "ق"),
    "Lam":      ("lam",     "ل"),
    "Meem":     ("meem",    "م"),
    "Nuun":     ("noon",    "ن"),
    "Nuungh":   ("nuungh",  "نغ"),
    "Pay":      ("pay",     "پ"),
    "Ray":      ("ray",     "ر"),
    "Say":      ("say",     "ث"),
    "Seen":     ("seen",    "س"),
    "Sheen":    ("sheen",   "ش"),
    "Suad":     ("suad",    "ص"),
    "Taay":     ("taay",    "ط"),
    "Tay":      ("tay",     "ت"),
    "Tuey":     ("tuey",    "ٹ"),
    "Wao":      ("wao",     "و"),
    "Zaal":     ("zaal",    "ذ"),
    "Zaey":     ("zaey",    "ز"),
    "Zay":      ("zay",     "ز"),
    "Zuad":     ("zuad",    "ض"),
    "Zuey":     ("zuey",    "ظ"),
}


def get_urdu_script(label: str, mode: str = "word") -> str:
    """Returns Urdu script. mode: word, alpha, urdu_alpha."""
    if mode == "alpha":
        return ALPHA_LABELS.get(label.upper(), (label, label))[1]
    if mode == "urdu_alpha":
        return URDU_ALPHA_LABELS.get(label, (label, label))[1]
    return WORD_LABELS.get(label, (label, label))[1]


def get_roman_urdu(label: str, mode: str = "word") -> str:
    """Returns Roman Urdu. mode: word, alpha, urdu_alpha."""
    if mode == "alpha":
        return ALPHA_LABELS.get(label.upper(), (label, label))[0]
    if mode == "urdu_alpha":
        return URDU_ALPHA_LABELS.get(label, (label, label))[0]
    return WORD_LABELS.get(label, (label, label))[0]
